package com.fhfelipefh.sandstorm.content.item;

import com.fhfelipefh.sandstorm.content.block.SandStormBlocks;
import com.fhfelipefh.sandstorm.content.entity.SandStormEntities;
import com.fhfelipefh.sandstorm.content.storage.QuantumStorageCartridgeItem;
import com.fhfelipefh.sandstorm.content.storage.StorageCartridgeTier;
import com.fhfelipefh.sandstorm.core.SandStormMod;
import net.fabricmc.fabric.api.creativetab.v1.FabricCreativeModeTab;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.ToolMaterial;
import net.minecraft.world.item.equipment.ArmorType;

public class SandStormItems {
    public static ResourceKey<Item> itemKey(String path) {
        return SandStormMod.itemKey(path);
    }

    public static Item.Properties properties(String path) {
        return new Item.Properties().setId(itemKey(path));
    }

    public static final SpaceRationItem SPACE_RATION = register("space_ration", new SpaceRationItem(properties("space_ration")));
    public static final SpaceSuitItem SPACE_SUIT_HELMET = register("space_suit_helmet", new SpaceSuitItem(ArmorType.HELMET, properties("space_suit_helmet")));
    public static final SpaceSuitItem SPACE_SUIT_CHESTPLATE = register("space_suit_chestplate", new SpaceSuitItem(ArmorType.CHESTPLATE, properties("space_suit_chestplate")));
    public static final SpaceSuitItem SPACE_SUIT_LEGGINGS = register("space_suit_leggings", new SpaceSuitItem(ArmorType.LEGGINGS, properties("space_suit_leggings")));
    public static final SpaceSuitItem SPACE_SUIT_BOOTS = register("space_suit_boots", new SpaceSuitItem(ArmorType.BOOTS, properties("space_suit_boots")));
    public static final BrackishWaterBottleItem BRACKISH_WATER_BOTTLE = register("brackish_water_bottle", new BrackishWaterBottleItem(properties("brackish_water_bottle")));
    public static final Item SANDWORM_CHITIN = register("sandworm_chitin", new Item(properties("sandworm_chitin").rarity(Rarity.UNCOMMON)));
    public static final Item SANDWORM_TOOTH = register("sandworm_tooth", new Item(properties("sandworm_tooth").rarity(Rarity.RARE)));
    public static final Item RAW_SILICON = register("raw_silicon", new Item(properties("raw_silicon")));
    public static final Item TOOL_BASE = register("tool_base", new Item(properties("tool_base")));
    public static final Item ELECTRIC_COMPONENT = register("electric_component", new Item(properties("electric_component").rarity(Rarity.UNCOMMON)));
    public static final Item SILICON_PICKAXE = register("silicon_pickaxe", new Item(properties("silicon_pickaxe").pickaxe(ToolMaterial.IRON, 1.0f, -2.8f).rarity(Rarity.UNCOMMON)));
    public static final Item SILICON_WAFER = register("silicon_wafer", new Item(properties("silicon_wafer")));
    public static final Item MINERAL_SALT = register("mineral_salt", new Item(properties("mineral_salt")));
    public static final PotableWaterBottleItem POTABLE_WATER_BOTTLE = register("potable_water_bottle", new PotableWaterBottleItem(properties("potable_water_bottle")));
    public static final Item CIRCUIT_BOARD = register("circuit_board", new Item(properties("circuit_board").rarity(Rarity.UNCOMMON)));
    public static final Item NANO_ACTUATOR = register("nano_actuator", new Item(properties("nano_actuator").rarity(Rarity.RARE)));
    public static final AnomalyRadarItem ANOMALY_RADAR = register("anomaly_radar", new AnomalyRadarItem(properties("anomaly_radar")));
    public static final Item TECH_DISC = register("tech_disc", new Item(properties("tech_disc").rarity(Rarity.RARE)));
    public static final Item SCRAP_METAL = register("scrap_metal", new Item(properties("scrap_metal").rarity(Rarity.UNCOMMON)));
    public static final SonicCannonItem SONIC_CANNON = register("sonic_cannon", new SonicCannonItem(properties("sonic_cannon")));
    public static final PlasmaRifleItem PLASMA_RIFLE = register("plasma_rifle", new PlasmaRifleItem(properties("plasma_rifle")));
    public static final VibroCrysknifeItem VIBRO_CRYSKNIFE = register("vibro_crysknife", new VibroCrysknifeItem(properties("vibro_crysknife")));
    public static final AtmosphericAnalyzerItem ATMOSPHERIC_ANALYZER = register("atmospheric_analyzer", new AtmosphericAnalyzerItem(properties("atmospheric_analyzer")));
    public static final SurvivalDatapadItem SURVIVAL_DATAPAD = register("survival_datapad", new SurvivalDatapadItem(properties("survival_datapad").rarity(Rarity.RARE).stacksTo(1)));
    public static final NutrientBombItem NUTRIENT_BOMB = register("nutrient_bomb", new NutrientBombItem(properties("nutrient_bomb").stacksTo(16)));
    public static final FilterCartridgeItem FILTER_CARTRIDGE = register("filter_cartridge", new FilterCartridgeItem(properties("filter_cartridge").durability(1000).rarity(Rarity.UNCOMMON)));
    public static final TechBucketItem TECH_BUCKET = register("tech_bucket", new TechBucketItem(properties("tech_bucket").stacksTo(1).rarity(Rarity.RARE)));
    public static final SuitUpgradeItem SUIT_UPGRADE_BATTERY = register("suit_upgrade_battery", new SuitUpgradeItem(SuitUpgradeItem.UpgradeType.BATTERY, properties("suit_upgrade_battery").rarity(Rarity.RARE).stacksTo(1)));
    public static final SuitUpgradeItem SUIT_UPGRADE_THERMAL = register("suit_upgrade_thermal", new SuitUpgradeItem(SuitUpgradeItem.UpgradeType.THERMAL, properties("suit_upgrade_thermal").rarity(Rarity.RARE).stacksTo(1)));
    public static final SuitUpgradeItem SUIT_UPGRADE_SEISMIC = register("suit_upgrade_seismic", new SuitUpgradeItem(SuitUpgradeItem.UpgradeType.SEISMIC, properties("suit_upgrade_seismic").rarity(Rarity.RARE).stacksTo(1)));
    public static final SuitUpgradeItem SUIT_UPGRADE_VISOR = register("suit_upgrade_visor", new SuitUpgradeItem(SuitUpgradeItem.UpgradeType.VISOR, properties("suit_upgrade_visor").rarity(Rarity.RARE).stacksTo(1)));
    public static final SuitUpgradeItem SUIT_UPGRADE_JETPACK = register("suit_upgrade_jetpack", new SuitUpgradeItem(SuitUpgradeItem.UpgradeType.JETPACK, properties("suit_upgrade_jetpack").rarity(Rarity.EPIC).stacksTo(1)));
    public static final Item EMPTY_CARTRIDGE = register("empty_cartridge", new Item(properties("empty_cartridge").rarity(Rarity.UNCOMMON)));
    public static final PropellantCartridgeItem PROPELLANT_CARTRIDGE = register("propellant_cartridge", new PropellantCartridgeItem(properties("propellant_cartridge").rarity(Rarity.RARE).stacksTo(16)));
    public static final SandboardItem SANDBOARD = register("sandboard", new SandboardItem(properties("sandboard").rarity(Rarity.RARE).stacksTo(1)));
    public static final SpawnEggItem SANDWORM_SPAWN_EGG = register("sandworm_spawn_egg", new SpawnEggItem(properties("sandworm_spawn_egg").spawnEgg(SandStormEntities.SANDWORM)));
    public static final XenoGrassSeedsItem XENO_GRASS_SEEDS = register("xeno_grass_seeds", new XenoGrassSeedsItem(properties("xeno_grass_seeds")));
    public static final SamplingSyringeItem SAMPLING_SYRINGE = register("sampling_syringe", new SamplingSyringeItem(properties("sampling_syringe").stacksTo(1)));
    public static final HeavySapBottleItem HEAVY_SAP_BOTTLE = register("heavy_sap_bottle", new HeavySapBottleItem(properties("heavy_sap_bottle")));
    public static final Item FLEXIBLE_BIOPOLYMER = register("flexible_biopolymer", new Item(properties("flexible_biopolymer").rarity(Rarity.UNCOMMON)));
    public static final Item PIEZO_QUARTZ_SHARD = register("piezo_quartz_shard", new Item(properties("piezo_quartz_shard").rarity(Rarity.UNCOMMON)));
    public static final Item PIEZO_RESONATOR = register("piezo_resonator", new Item(properties("piezo_resonator").rarity(Rarity.RARE)));
    public static final Item PRESSURIZED_FOSSIL_FLUID_BUCKET = register("pressurized_fossil_fluid_bucket", new Item(properties("pressurized_fossil_fluid_bucket").craftRemainder(Items.BUCKET).stacksTo(1).rarity(Rarity.UNCOMMON)));
    public static final Item TITANIUM_CHITIN_COMPOSITE = register("titanium_chitin_composite", new Item(properties("titanium_chitin_composite").rarity(Rarity.RARE)));
    public static final HeavyPlasmaCannonItem HEAVY_PLASMA_CANNON = register("heavy_plasma_cannon", new HeavyPlasmaCannonItem(properties("heavy_plasma_cannon")));
    public static final OrbitalSurveySatelliteItem ORBITAL_SURVEY_SATELLITE = register("orbital_survey_satellite", new OrbitalSurveySatelliteItem(properties("orbital_survey_satellite")));
    public static final Item ANCIENT_REED = register("ancient_reed", new Item(properties("ancient_reed")));
    public static final Item ANCIENT_SEED = register("ancient_seed", new Item(properties("ancient_seed")));
    public static final Item GEOLOGICAL_SCANNER = register("geological_scanner", new Item(properties("geological_scanner").rarity(Rarity.UNCOMMON)));
    public static final Item FIELD_PROBE = register("field_probe", new Item(properties("field_probe").rarity(Rarity.UNCOMMON)));
    public static final Item REPAIR_TOOL = register("repair_tool", new Item(properties("repair_tool").rarity(Rarity.UNCOMMON)));
    public static final Item STRUCTURAL_PLATE = register("structural_plate", new Item(properties("structural_plate").rarity(Rarity.UNCOMMON)));
    public static final Item CIRCUIT_MOUNT = register("circuit_mount", new Item(properties("circuit_mount").rarity(Rarity.UNCOMMON)));
    public static final Item PRESSURE_SEAL = register("pressure_seal", new Item(properties("pressure_seal").rarity(Rarity.UNCOMMON)));
    public static final Item RADIOPROTECTIVE_MELANIN = register("radioprotective_melanin", new Item(properties("radioprotective_melanin").rarity(Rarity.UNCOMMON)));
    public static final Item CHITOSAN_EXTRACT = register("chitosan_extract", new Item(properties("chitosan_extract").rarity(Rarity.UNCOMMON)));
    public static final Item TREHALOSE_SUGAR = register("trehalose_sugar", new Item(properties("trehalose_sugar").rarity(Rarity.UNCOMMON)));
    public static final Item OSMOLYTE_GLYCEROL = register("osmolyte_glycerol", new Item(properties("osmolyte_glycerol").rarity(Rarity.UNCOMMON)));
    public static final Item NEUROACTIVE_ALKALOIDS = register("neuroactive_alkaloids", new Item(properties("neuroactive_alkaloids").rarity(Rarity.UNCOMMON)));
    public static final HypoInjectorItem HYPO_INJECTOR = register("hypo_injector", new HypoInjectorItem(properties("hypo_injector")));
    public static final PharmacologicalStimItem ADRENAL_STIM = register("adrenal_stim", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.ADRENAL, properties("adrenal_stim")));
    public static final PharmacologicalStimItem BIOFOAM_CARTRIDGE = register("biofoam_cartridge", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.BIOFOAM, properties("biofoam_cartridge")));
    public static final PharmacologicalStimItem MYOMER_STIM = register("myomer_stim", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.MYOMER, properties("myomer_stim")));
    public static final PharmacologicalStimItem ENDOTHERMIC_SERUM = register("endothermic_serum", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.ENDOTHERMIC, properties("endothermic_serum")));
    public static final PharmacologicalStimItem GRAV_DAMPENER_STIM = register("grav_dampener_stim", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.GRAV_DAMPENER, properties("grav_dampener_stim")));
    public static final PharmacologicalStimItem DETOX_AMPOULE = register("detox_ampoule", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.DETOX, properties("detox_ampoule")));
    public static final PharmacologicalStimItem STEALTH_NANO_DRAPE = register("stealth_nano_drape", new PharmacologicalStimItem(PharmacologicalStimItem.StimType.STEALTH, properties("stealth_nano_drape")));
    public static final MolecularUpgradeItem VIBRO_RESONATOR_MODULE = register("vibro_resonator_module", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.VIBRO_RESONATOR, properties("vibro_resonator_module").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem THERMAL_PLASMA_EMITTER = register("thermal_plasma_emitter", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.THERMAL_PLASMA, properties("thermal_plasma_emitter").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem KINETIC_FOCUS_MODULE = register("kinetic_focus_module", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.KINETIC_FOCUS, properties("kinetic_focus_module").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem CAVITATION_FREQUENCY_CORE = register("cavitation_frequency_core", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.CAVITATION_CORE, properties("cavitation_frequency_core").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem ATOMIC_PHASE_DISRUPTER = register("atomic_phase_disrupter", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.ATOMIC_PHASE, properties("atomic_phase_disrupter").rarity(Rarity.EPIC)));
    public static final MolecularUpgradeItem SPECTROMETRIC_SIFTER = register("spectrometric_sifter", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.SPECTROMETRIC_SIFTER, properties("spectrometric_sifter").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem SELF_HEALING_NANITE_MATRIX = register("self_healing_nanite_matrix", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.SELF_HEALING_NANITES, properties("self_healing_nanite_matrix").rarity(Rarity.EPIC)));
    public static final MolecularUpgradeItem TITANIUM_LATTICE_COATING = register("titanium_lattice_coating", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.TITANIUM_LATTICE, properties("titanium_lattice_coating").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem BALLISTIC_DAMPENER_MESH = register("ballistic_dampener_mesh", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.BALLISTIC_DAMPENER, properties("ballistic_dampener_mesh").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem ABLATIVE_THERMAL_PLATING = register("ablative_thermal_plating", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.ABLATIVE_PLATING, properties("ablative_thermal_plating").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem PNEUMATIC_FALL_DAMPERS = register("pneumatic_fall_dampers", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.FALL_DAMPERS, properties("pneumatic_fall_dampers").rarity(Rarity.RARE)));
    public static final MolecularUpgradeItem REACTIVE_SHOCK_PLATING = register("reactive_shock_plating", new MolecularUpgradeItem(MolecularUpgradeItem.UpgradeType.REACTIVE_SHOCK, properties("reactive_shock_plating").rarity(Rarity.RARE)));
    public static final Item BIOMECHANICAL_CHASSIS_FRAME = register("biomechanical_chassis_frame", new Item(properties("biomechanical_chassis_frame").rarity(Rarity.RARE)));
    public static final Item SYNTHETIC_MYOMER_BUNDLE = register("synthetic_myomer_bundle", new Item(properties("synthetic_myomer_bundle").rarity(Rarity.RARE)));
    public static final Item BIO_NEURAL_CORE = register("bio_neural_core", new Item(properties("bio_neural_core").rarity(Rarity.EPIC)));
    public static final Item BIO_COOLANT_CANISTER = register("bio_coolant_canister", new Item(properties("bio_coolant_canister").rarity(Rarity.UNCOMMON)));
    public static final Item ASSEMBLED_CYBORG_FRAME = register("assembled_cyborg_frame", new Item(properties("assembled_cyborg_frame").rarity(Rarity.EPIC)));
    public static final CyberneticCommandUplinkItem CYBERNETIC_COMMAND_UPLINK = register("cybernetic_command_uplink", new CyberneticCommandUplinkItem(properties("cybernetic_command_uplink").rarity(Rarity.EPIC).stacksTo(1)));
    public static final SpawnEggItem CYBORG_EXCAVATOR_SPAWN_EGG = register("cyborg_excavator_spawn_egg", new SpawnEggItem(properties("cyborg_excavator_spawn_egg").spawnEgg(SandStormEntities.CYBORG_EXCAVATOR)));
    public static final SpawnEggItem CYBORG_BUILDER_SPAWN_EGG = register("cyborg_builder_spawn_egg", new SpawnEggItem(properties("cyborg_builder_spawn_egg").spawnEgg(SandStormEntities.CYBORG_BUILDER)));
    public static final SpawnEggItem CYBORG_HARVESTER_SPAWN_EGG = register("cyborg_harvester_spawn_egg", new SpawnEggItem(properties("cyborg_harvester_spawn_egg").spawnEgg(SandStormEntities.CYBORG_HARVESTER)));
    public static final SpawnEggItem SCRAP_SENTINEL_SPAWN_EGG = register("scrap_sentinel_spawn_egg", new SpawnEggItem(properties("scrap_sentinel_spawn_egg").spawnEgg(SandStormEntities.SCRAP_SENTINEL)));
    public static final SpawnEggItem AQUIFER_BEETLE_SPAWN_EGG = register("aquifer_beetle_spawn_egg", new SpawnEggItem(properties("aquifer_beetle_spawn_egg").spawnEgg(SandStormEntities.AQUIFER_BEETLE)));
    public static final SpawnEggItem NOMAD_SCAVENGER_SPAWN_EGG = register("nomad_scavenger_spawn_egg", new SpawnEggItem(properties("nomad_scavenger_spawn_egg").spawnEgg(SandStormEntities.NOMAD_SCAVENGER)));
    public static final Item LOOSE_WIRES = register("loose_wires", new Item(properties("loose_wires").rarity(Rarity.COMMON)));
    public static final Item WORTHLESS_SCRAP = register("worthless_scrap", new Item(properties("worthless_scrap").rarity(Rarity.COMMON)));
    public static final Item SALT_GLAND = register("salt_gland", new Item(properties("salt_gland").rarity(Rarity.UNCOMMON)));
    public static final Item THERMAL_CARAPACE = register("thermal_carapace", new Item(properties("thermal_carapace").rarity(Rarity.RARE)));
    public static final CyborgUpgradeItem ACID_CHITIN_PLATING = register("acid_chitin_plating", new CyborgUpgradeItem(CyborgUpgradeItem.CyborgUpgradeType.ACID_CHITIN_PLATING, properties("acid_chitin_plating")));
    public static final CyborgUpgradeItem CRYO_TREHALOSE_CELL = register("cryo_trehalose_cell", new CyborgUpgradeItem(CyborgUpgradeItem.CyborgUpgradeType.CRYO_TREHALOSE_CELL, properties("cryo_trehalose_cell")));
    public static final CyborgUpgradeItem LONG_RANGE_LIDAR_LENS = register("long_range_lidar_lens", new CyborgUpgradeItem(CyborgUpgradeItem.CyborgUpgradeType.LONG_RANGE_LIDAR_LENS, properties("long_range_lidar_lens")));
    public static final CyborgUpgradeItem PIEZO_HOVER_THRUSTER = register("piezo_hover_thruster", new CyborgUpgradeItem(CyborgUpgradeItem.CyborgUpgradeType.PIEZO_HOVER_THRUSTER, properties("piezo_hover_thruster")));
    public static final Item NEURAL_SYNAPSE_LINK = register("neural_synapse_link", new Item(properties("neural_synapse_link").rarity(Rarity.EPIC).stacksTo(1)));
    public static final Item ORBITAL_RECON_PROBE = register("orbital_recon_probe", new Item(properties("orbital_recon_probe").rarity(Rarity.RARE).stacksTo(16)));
    public static final Item QUANTUM_MIND_MATRIX = register("quantum_mind_matrix", new Item(properties("quantum_mind_matrix").rarity(Rarity.EPIC)));
    public static final Item KINETIC_SLUG = register("kinetic_slug", new Item(properties("kinetic_slug").rarity(Rarity.UNCOMMON).stacksTo(64)));
    public static final Item SUPERCONDUCTOR_TOROID = register("superconductor_toroid", new Item(properties("superconductor_toroid").rarity(Rarity.RARE).stacksTo(16)));
    public static final Item PLASMA_FOCUS_CRYSTAL = register("plasma_focus_crystal", new Item(properties("plasma_focus_crystal").rarity(Rarity.EPIC).stacksTo(16)));
    public static final Item GEOTHERMAL_CORE_DRILL_BIT = register("geothermal_core_drill_bit", new Item(properties("geothermal_core_drill_bit").rarity(Rarity.RARE).stacksTo(16)));
    public static final Item MANTLE_ALLOY_INGOT = register("mantle_alloy_ingot", new Item(properties("mantle_alloy_ingot").rarity(Rarity.EPIC)));
    public static final Item SUPERHEATED_LITHIUM_CAPSULE = register("superheated_lithium_capsule", new Item(properties("superheated_lithium_capsule").rarity(Rarity.RARE).stacksTo(16)));
    public static final Item THERMAL_RADIATOR_FIN = register("thermal_radiator_fin", new Item(properties("thermal_radiator_fin").rarity(Rarity.UNCOMMON).stacksTo(64)));
    public static final Item RAW_LITHIUM_SALTS = register("raw_lithium_salts", new Item(properties("raw_lithium_salts").rarity(Rarity.UNCOMMON).stacksTo(64)));
    public static final Item MEGAZORD_FLIGHT_MODULE = register("megazord_flight_module", new Item(properties("megazord_flight_module").rarity(Rarity.EPIC).stacksTo(1)));
    public static final Item MEGAZORD_SUBMERSIBLE_HULL = register("megazord_submersible_hull", new Item(properties("megazord_submersible_hull").rarity(Rarity.EPIC).stacksTo(1)));
    public static final Item MEGAZORD_TACTICAL_OVERDRIVE = register("megazord_tactical_overdrive", new Item(properties("megazord_tactical_overdrive").rarity(Rarity.EPIC).stacksTo(1)));
    public static final Item VECTORED_THRUSTER = register("vectored_thruster", new Item(properties("vectored_thruster").rarity(Rarity.RARE).stacksTo(16)));
    public static final Item HYDRO_BALLAST_PUMP = register("hydro_ballast_pump", new Item(properties("hydro_ballast_pump").rarity(Rarity.RARE).stacksTo(16)));
    public static final WeatherReconSatelliteItem WEATHER_RECON_SATELLITE = register("weather_recon_satellite", new WeatherReconSatelliteItem(properties("weather_recon_satellite").rarity(Rarity.RARE).stacksTo(16)));
    public static final OrbitalSolarReflectorSatelliteItem ORBITAL_SOLAR_REFLECTOR_SATELLITE = register("orbital_solar_reflector_satellite", new OrbitalSolarReflectorSatelliteItem(properties("orbital_solar_reflector_satellite").rarity(Rarity.RARE).stacksTo(16)));
    public static final SarGeologicalSatelliteItem SAR_GEOLOGICAL_SATELLITE = register("sar_geological_satellite", new SarGeologicalSatelliteItem(properties("sar_geological_satellite").rarity(Rarity.RARE).stacksTo(16)));
    public static final OrbitalKineticLanceSatelliteItem ORBITAL_KINETIC_LANCE_SATELLITE = register("orbital_kinetic_lance_satellite", new OrbitalKineticLanceSatelliteItem(properties("orbital_kinetic_lance_satellite").rarity(Rarity.EPIC).stacksTo(16)));
    public static final AdvancedRefractionLensItem ADVANCED_REFRACTION_LENS = register("advanced_refraction_lens", new AdvancedRefractionLensItem(properties("advanced_refraction_lens").rarity(Rarity.RARE).stacksTo(16)));
    public static final Item QUANTUM_PROCESSOR = register("quantum_processor", new Item(properties("quantum_processor").rarity(Rarity.RARE)));
    public static final Item STORAGE_HOUSING = register("storage_housing", new Item(properties("storage_housing").rarity(Rarity.UNCOMMON)));
    public static final QuantumStorageCartridgeItem QUANTUM_STORAGE_CARTRIDGE_1K = register("quantum_storage_cartridge_1k", new QuantumStorageCartridgeItem(StorageCartridgeTier.TIER_1K, properties("quantum_storage_cartridge_1k").stacksTo(1).rarity(Rarity.COMMON)));
    public static final QuantumStorageCartridgeItem QUANTUM_STORAGE_CARTRIDGE_4K = register("quantum_storage_cartridge_4k", new QuantumStorageCartridgeItem(StorageCartridgeTier.TIER_4K, properties("quantum_storage_cartridge_4k").stacksTo(1).rarity(Rarity.UNCOMMON)));
    public static final QuantumStorageCartridgeItem QUANTUM_STORAGE_CARTRIDGE_16K = register("quantum_storage_cartridge_16k", new QuantumStorageCartridgeItem(StorageCartridgeTier.TIER_16K, properties("quantum_storage_cartridge_16k").stacksTo(1).rarity(Rarity.RARE)));
    public static final QuantumStorageCartridgeItem QUANTUM_STORAGE_CARTRIDGE_64K = register("quantum_storage_cartridge_64k", new QuantumStorageCartridgeItem(StorageCartridgeTier.TIER_64K, properties("quantum_storage_cartridge_64k").stacksTo(1).rarity(Rarity.EPIC)));
    public static final QuantumStorageCartridgeItem QUANTUM_STORAGE_CARTRIDGE_DIMENSIONAL = register("quantum_storage_cartridge_dimensional", new QuantumStorageCartridgeItem(StorageCartridgeTier.DIMENSIONAL, properties("quantum_storage_cartridge_dimensional").stacksTo(1).rarity(Rarity.EPIC)));

    public static final CreativeModeTab SANDSTORM_TAB = Registry.register(
            BuiltInRegistries.CREATIVE_MODE_TAB,
            SandStormMod.id("general"),
            FabricCreativeModeTab.builder()
                    .icon(() -> new ItemStack(SPACE_SUIT_CHESTPLATE))
                    .title(Component.translatable("itemGroup.sandstorm.general"))
                    .displayItems((context, entries) -> {
                        entries.accept(SURVIVAL_DATAPAD);
                        entries.accept(SPACE_RATION);
                        entries.accept(SPACE_SUIT_HELMET);
                        entries.accept(SPACE_SUIT_CHESTPLATE);
                        entries.accept(SPACE_SUIT_LEGGINGS);
                        entries.accept(SPACE_SUIT_BOOTS);
                        entries.accept(SUIT_UPGRADE_BATTERY);
                        entries.accept(SUIT_UPGRADE_THERMAL);
                        entries.accept(SUIT_UPGRADE_SEISMIC);
                        entries.accept(SUIT_UPGRADE_VISOR);
                        entries.accept(SUIT_UPGRADE_JETPACK);
                        entries.accept(EMPTY_CARTRIDGE);
                        entries.accept(PROPELLANT_CARTRIDGE);
                        entries.accept(SANDBOARD);
                        entries.accept(BRACKISH_WATER_BOTTLE);
                        entries.accept(POTABLE_WATER_BOTTLE);
                        entries.accept(MINERAL_SALT);
                        entries.accept(RAW_SILICON);
                        entries.accept(TOOL_BASE);
                        entries.accept(ELECTRIC_COMPONENT);
                        entries.accept(SILICON_PICKAXE);
                        entries.accept(SILICON_WAFER);
                        entries.accept(CIRCUIT_BOARD);
                        entries.accept(NANO_ACTUATOR);
                        entries.accept(FILTER_CARTRIDGE);
                        entries.accept(TECH_BUCKET);
                        entries.accept(ANOMALY_RADAR);
                        entries.accept(TECH_DISC);
                        entries.accept(SCRAP_METAL);
                        entries.accept(SONIC_CANNON);
                        entries.accept(PLASMA_RIFLE);
                        entries.accept(VIBRO_CRYSKNIFE);
                        entries.accept(ATMOSPHERIC_ANALYZER);
                        entries.accept(SandStormBlocks.SANDSTONE_WORKBENCH);
                        entries.accept(SandStormBlocks.SANDSTONE_FURNACE);
                        entries.accept(SandStormBlocks.BRACKISH_AQUIFER);
                        entries.accept(SandStormBlocks.THUMPER);
                        entries.accept(SandStormBlocks.PRINTER_3D);
                        entries.accept(SandStormBlocks.DESALINATION_FILTER);
                        entries.accept(SandStormBlocks.DEW_CONDENSER);
                        entries.accept(SandStormBlocks.NANITE_FABRICATOR);
                        entries.accept(SandStormBlocks.CHEMICAL_REFINERY);
                        entries.accept(SandStormBlocks.FLUID_PIPE);
                        entries.accept(SandStormBlocks.BURIED_TECH_RUINS);
                        entries.accept(SandStormBlocks.ANCIENT_DATA_CORE);
                        entries.accept(SandStormBlocks.DRONE_DOCK);
                        entries.accept(SandStormBlocks.ASSEMBLY_BAY);
                        entries.accept(SandStormBlocks.ATMOSPHERIC_TERRAFORMER);
                        entries.accept(SandStormBlocks.WIRELESS_SOLAR_RECEIVER);
                        entries.accept(SandStormBlocks.WIRELESS_SOLAR_RECEIVER_TIER2);
                        entries.accept(SandStormBlocks.THERMAL_GENERATOR);
                        entries.accept(SandStormBlocks.WPT_RELAY_TOWER);
                        entries.accept(SandStormBlocks.SOLID_STATE_ACCUMULATOR);
                        entries.accept(SandStormBlocks.SMART_FLUID_PIPE);
                        entries.accept(SandStormBlocks.GRID_MONITOR_CONSOLE);
                        entries.accept(NUTRIENT_BOMB);
                        entries.accept(XENO_GRASS_SEEDS);
                        entries.accept(SAMPLING_SYRINGE);
                        entries.accept(HEAVY_SAP_BOTTLE);
                        entries.accept(FLEXIBLE_BIOPOLYMER);
                        entries.accept(SandStormBlocks.HYDROPONIC_CHAMBER);
                        entries.accept(SandStormBlocks.XENO_GRASS_BLOCK);
                        entries.accept(SandStormBlocks.HEAVY_SAP_CACTUS);
                        entries.accept(SandStormBlocks.SALINIZED_SAND);
                        entries.accept(SandStormBlocks.HALOPHYTE_PLANT);
                        entries.accept(SANDWORM_CHITIN);
                        entries.accept(SANDWORM_TOOTH);
                        entries.accept(SANDWORM_SPAWN_EGG);
                        entries.accept(PIEZO_QUARTZ_SHARD);
                        entries.accept(PIEZO_RESONATOR);
                        entries.accept(PRESSURIZED_FOSSIL_FLUID_BUCKET);
                        entries.accept(SandStormBlocks.PIEZO_QUARTZ_BLOCK);
                        entries.accept(SandStormBlocks.BUDDING_PIEZO_QUARTZ);
                        entries.accept(SandStormBlocks.PIEZO_QUARTZ_CLUSTER);
                        entries.accept(SandStormBlocks.DEEP_CORE_DRILL);
                        entries.accept(TITANIUM_CHITIN_COMPOSITE);
                        entries.accept(HEAVY_PLASMA_CANNON);
                        entries.accept(ORBITAL_SURVEY_SATELLITE);
                        entries.accept(SandStormBlocks.THERMAL_SPRING_STONE);
                        entries.accept(SandStormBlocks.ELECTRIFIED_SAND);
                        entries.accept(SandStormBlocks.FOSSILIZED_AMBER);
                        entries.accept(SandStormBlocks.FULGURITE_GLASS);
                        entries.accept(SandStormBlocks.ANCIENT_REED_BLOCK);
                        entries.accept(ANCIENT_REED);
                        entries.accept(ANCIENT_SEED);
                        entries.accept(SandStormBlocks.KINETIC_SHIELD_GENERATOR);
                        entries.accept(SandStormBlocks.SAND_MAGLEV_RAIL);
                        entries.accept(SandStormBlocks.HABITAT_DOME);
                        entries.accept(SandStormBlocks.AUTO_ASSEMBLY_LINE);
                        entries.accept(SandStormBlocks.TITANIUM_SPIKE_WALL);
                        entries.accept(SandStormBlocks.RETRACTABLE_SPIKE_WALL);
                        entries.accept(SandStormBlocks.ELECTRIFIED_SPIKE_BARRIER);
                        entries.accept(SandStormBlocks.CORROSIVE_CHITIN_SPIKE_WALL);
                        entries.accept(SandStormBlocks.KINETIC_FLOOR_SPIKES);
                        entries.accept(SandStormBlocks.CRUSHING_SPIKE_GATE);
                        entries.accept(SandStormBlocks.MEGASTRUCTURE_CONSTRUCTOR);
                        entries.accept(GEOLOGICAL_SCANNER);
                        entries.accept(FIELD_PROBE);
                        entries.accept(REPAIR_TOOL);
                        entries.accept(STRUCTURAL_PLATE);
                        entries.accept(CIRCUIT_MOUNT);
                        entries.accept(PRESSURE_SEAL);
                        entries.accept(RADIOPROTECTIVE_MELANIN);
                        entries.accept(CHITOSAN_EXTRACT);
                        entries.accept(TREHALOSE_SUGAR);
                        entries.accept(OSMOLYTE_GLYCEROL);
                        entries.accept(NEUROACTIVE_ALKALOIDS);
                        entries.accept(SandStormBlocks.RADIOTROPHIC_MYCELIUM);
                        entries.accept(SandStormBlocks.CHITINOLYTIC_FUNGUS);
                        entries.accept(SandStormBlocks.CRYO_XEROPHILIC_LICHEN);
                        entries.accept(SandStormBlocks.HALOPHYTE_SUCCULENT);
                        entries.accept(SandStormBlocks.DUNE_EPHEDRA);
                        entries.accept(SandStormBlocks.BIOREACTOR_VAT);
                        entries.accept(HYPO_INJECTOR);
                        entries.accept(ADRENAL_STIM);
                        entries.accept(BIOFOAM_CARTRIDGE);
                        entries.accept(MYOMER_STIM);
                        entries.accept(ENDOTHERMIC_SERUM);
                        entries.accept(GRAV_DAMPENER_STIM);
                        entries.accept(DETOX_AMPOULE);
                        entries.accept(STEALTH_NANO_DRAPE);
                        entries.accept(SandStormBlocks.MOLECULAR_MODIFIER);
                        entries.accept(VIBRO_RESONATOR_MODULE);
                        entries.accept(THERMAL_PLASMA_EMITTER);
                        entries.accept(KINETIC_FOCUS_MODULE);
                        entries.accept(CAVITATION_FREQUENCY_CORE);
                        entries.accept(ATOMIC_PHASE_DISRUPTER);
                        entries.accept(SPECTROMETRIC_SIFTER);
                        entries.accept(SELF_HEALING_NANITE_MATRIX);
                        entries.accept(TITANIUM_LATTICE_COATING);
                        entries.accept(BALLISTIC_DAMPENER_MESH);
                        entries.accept(ABLATIVE_THERMAL_PLATING);
                        entries.accept(PNEUMATIC_FALL_DAMPERS);
                        entries.accept(REACTIVE_SHOCK_PLATING);
                        entries.accept(SandStormBlocks.BIO_REGENERATION_POD);
                        entries.accept(SandStormBlocks.CYBORG_INCUBATOR_VAT);
                        entries.accept(BIOMECHANICAL_CHASSIS_FRAME);
                        entries.accept(SYNTHETIC_MYOMER_BUNDLE);
                        entries.accept(BIO_NEURAL_CORE);
                        entries.accept(BIO_COOLANT_CANISTER);
                        entries.accept(ASSEMBLED_CYBORG_FRAME);
                        entries.accept(CYBERNETIC_COMMAND_UPLINK);
                        entries.accept(CYBORG_EXCAVATOR_SPAWN_EGG);
                        entries.accept(CYBORG_BUILDER_SPAWN_EGG);
                        entries.accept(CYBORG_HARVESTER_SPAWN_EGG);
                        entries.accept(SCRAP_SENTINEL_SPAWN_EGG);
                        entries.accept(AQUIFER_BEETLE_SPAWN_EGG);
                        entries.accept(NOMAD_SCAVENGER_SPAWN_EGG);
                        entries.accept(LOOSE_WIRES);
                        entries.accept(WORTHLESS_SCRAP);
                        entries.accept(SALT_GLAND);
                        entries.accept(THERMAL_CARAPACE);
                        entries.accept(SandStormBlocks.CYBORG_DOCKING_STATION);
                        entries.accept(ACID_CHITIN_PLATING);
                        entries.accept(CRYO_TREHALOSE_CELL);
                        entries.accept(LONG_RANGE_LIDAR_LENS);
                        entries.accept(PIEZO_HOVER_THRUSTER);
                        entries.accept(SandStormBlocks.HOLO_TACTICAL_SPIRE);
                        entries.accept(NEURAL_SYNAPSE_LINK);
                        entries.accept(ORBITAL_RECON_PROBE);
                        entries.accept(SandStormBlocks.QUANTUM_SLEEPER_POD);
                        entries.accept(QUANTUM_MIND_MATRIX);
                        entries.accept(SandStormBlocks.PLASMA_SHIELD_GENERATOR);
                        entries.accept(SandStormBlocks.KINETIC_RAILGUN);
                        entries.accept(SandStormBlocks.ACOUSTIC_DEFENSE_PYLON);
                        entries.accept(SandStormBlocks.ELECTRIC_FENCE_PYLON);
                        entries.accept(SandStormBlocks.AUTONOMOUS_SONIC_TURRET);
                        entries.accept(KINETIC_SLUG);
                        entries.accept(SUPERCONDUCTOR_TOROID);
                        entries.accept(PLASMA_FOCUS_CRYSTAL);
                        entries.accept(SandStormBlocks.DEEP_CORE_BOREHOLE);
                        entries.accept(GEOTHERMAL_CORE_DRILL_BIT);
                        entries.accept(RAW_LITHIUM_SALTS);
                        entries.accept(SandStormBlocks.LITHO_PLASMA_EXTRACTOR);
                        entries.accept(SUPERHEATED_LITHIUM_CAPSULE);
                        entries.accept(MANTLE_ALLOY_INGOT);
                        entries.accept(SandStormBlocks.SUPERCRITICAL_HEAT_EXCHANGER);
                        entries.accept(THERMAL_RADIATOR_FIN);
                        entries.accept(MEGAZORD_FLIGHT_MODULE);
                        entries.accept(MEGAZORD_SUBMERSIBLE_HULL);
                        entries.accept(MEGAZORD_TACTICAL_OVERDRIVE);
                        entries.accept(VECTORED_THRUSTER);
                        entries.accept(HYDRO_BALLAST_PUMP);
                        entries.accept(WEATHER_RECON_SATELLITE);
                        entries.accept(ORBITAL_SOLAR_REFLECTOR_SATELLITE);
                        entries.accept(SAR_GEOLOGICAL_SATELLITE);
                        entries.accept(ORBITAL_KINETIC_LANCE_SATELLITE);
                        entries.accept(SandStormBlocks.ORBITAL_MASS_DRIVER);
                        entries.accept(SandStormBlocks.ORBITAL_GROUND_STATION);
                        entries.accept(SandStormBlocks.SPECTRAL_SURVEY_TELESCOPE);
                        entries.accept(SandStormBlocks.SUBSPACE_GATEWAY);
                        entries.accept(ADVANCED_REFRACTION_LENS);
                        entries.accept(SandStormBlocks.SEISMIC_DAMPENER_PAVING);
                        entries.accept(SandStormBlocks.SALT_BRICKS);
                        entries.accept(SandStormBlocks.SALT_BRICK_STAIRS);
                        entries.accept(SandStormBlocks.SALT_BRICK_SLAB);
                        entries.accept(SandStormBlocks.SALT_BRICK_WALL);
                        entries.accept(QUANTUM_PROCESSOR);
                        entries.accept(STORAGE_HOUSING);
                        entries.accept(QUANTUM_STORAGE_CARTRIDGE_1K);
                        entries.accept(QUANTUM_STORAGE_CARTRIDGE_4K);
                        entries.accept(QUANTUM_STORAGE_CARTRIDGE_16K);
                        entries.accept(QUANTUM_STORAGE_CARTRIDGE_64K);
                        entries.accept(QUANTUM_STORAGE_CARTRIDGE_DIMENSIONAL);
                        entries.accept(SandStormBlocks.QUANTUM_NETWORK_CONTROLLER);
                        entries.accept(SandStormBlocks.QUANTUM_DISK_DRIVE);
                        entries.accept(SandStormBlocks.QUANTUM_ACCESS_TERMINAL);
                        entries.accept(SandStormBlocks.QUANTUM_NETWORK_CABLE);
                    })
                    .build()
    );

    public static <T extends Item> T register(String path, T item) {
        if (item instanceof BlockItem blockItem) {
            blockItem.registerBlocks(Item.BY_BLOCK, item);
        }
        return Registry.register(BuiltInRegistries.ITEM, SandStormMod.id(path), item);
    }

    public static void initialize() {
    }
}
